version: '2'
services:
  jhipsterpoc-app:
    image: jhipsterpoc
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mariadb://jhipsterpoc-mariadb:3306/jhipsterpoc
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://jhipsterpoc-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://jhipsterpoc-elasticsearch:9200
    ports:
      - 8080:8080
  jhipsterpoc-mariadb:
    extends:
      file: mariadb.yml
      service: jhipsterpoc-mariadb
  jhipsterpoc-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: jhipsterpoc-elasticsearch
